version: "3.6"

services:
  web:
    # image: node:$NODE_TAG
    # working_dir: /app
    # command: npm run $INSTANCE_TYPE
    build:
      context: ./cwt/extensions/js-exp-1/stack/nodejs
      args:
        - NODE_TAG=$NODE_TAG
        - NODE_SRC=./web
        - NODE_ENV=$INSTANCE_TYPE
    command: npm run $INSTANCE_TYPE
    ports:
      - "80:8000"
    volumes:
      - "./web:/app"
